project:
  # Dataset folder name under the root path
  name: "kidlang"

  # Where the dataset root comes from:
  # - If root_override is null, read from this env var.
  root_env: "MEG_DATA"  # This environment variable should hold the path that contains your dataset
  root_override: null   # e.g., "/mnt/meg" to bypass the env var

subjects:
  # If empty (or missing), process ALL subjects found in the BIDS root
  include: ["Y0312"]
  # Always skip these (useful to omit pilot/bad subs)
  exclude: []

plots:
  save_stim_plots: true     # default true; set to false to disable saving

# Optional selection filters (empty => all)
bids_selection:
  sessions: []    # e.g., ["01", "02"]
  tasks: []       # e.g., ["language"]
  runs: []        # e.g., [1, 2]
  splits: []         # e.g., ["01","02"] to constrain splits
  processings: []
