# docker-compose.yml  (Compose V2 – no top-level "version:" key)
services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: supersecret
      MARIADB_DATABASE: moodle
      MARIADB_USER: moodle
      MARIADB_PASSWORD: moodlepass
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db:/var/lib/mysql

  moodle:
    image: moodlehq/moodle-php-apache:8.3          # <— PHP 8.3
    entrypoint: ["docker-ssl.sh", "docker-php-entrypoint"]
    command: ["apache2-foreground"]
    ports:
      - "45000:443"    # Moodle
    depends_on: [db]
    environment:
      MOODLE_DATABASE_TYPE: mariadb
      MOODLE_DATABASE_HOST: db
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: moodlepass
      PHP_OPCACHE_ENABLE: "1"
      PHP_OPCACHE_MEMORY_CONSUMPTION: "256"
      PHP_OPCACHE_MAX_ACCELERATED_FILES: "20000"
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"   # set to 1 while developing
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata
      - ./certs:/certs:ro                 # mount certs read-only
      - ./ssl.conf:/etc/apache2/conf-enabled/ssl.conf:ro
      - ./docker-ssl.sh:/usr/local/bin/docker-ssl.sh:ro   # ← fixed line
