name: bids-validation-cron-job.yml
on:
  workflow_dispatch:
  push:
    branches: [ main ]
#  schedule:
#    - cron: "0 3 * * *" # nightly @ 03:00 UTC
  pull_request:

jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Upload cat pic to Box
        uses: benjaminejarrell/box-upload-gh-actions@v1.2
        id: BoxUpload
        with:
          box-client-sdk-config: ${{ secrets.BOX_CLIENT_SDK_CONFIG }}
          box-folder-id: 340371145702
          file: cat.png
